config/routes.rb
Rails.application.routes.draw do
  get '/' => 'users#index'

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  resources :users do
    resources :foods do
      collection { post :sort}
    end
  end

  resources :users do
    resources :exercises
  end

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :user
  validates :name, :presence => true
  validates :burned, :presence => true
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :user
  validates :name, :presence => true
  validates :calories, :presence => true
  acts_as_list
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :foods
  has_many :exercises

  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)

  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
  end

  helper_method :current_user
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @exercise = @user.exercises.new
  end

  def create
    @user = User.find(params[:user_id])
    @exercise = @user.exercises.new(exercise_params)
    if @exercise.save
      flash[:notice] = "Exercise added."
    else
      render :new
    end
    respond_to do |format|
      format.html { redirect_to user_exercises_path(@user, @exercise) }
      format.js
    end
  end

  def edit
    @user = current_user
    @exercise = Exercise.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @exercise = Exercise.find(params[:id])
    if @exercise.update(exercise_params)
      flash[:notice] = @exercise.name + ' has been updated.'
    else
      render :edit
    end
    respond_to do |format|
      format.html { redirect_to user_exercises_path(@user, @exercise) }
      format.js
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @exercise = Exercise.find(params[:id])
    @exercise.destroy
    flash[:notice] = @exercise.name + " has been removed."
    respond_to do |format|
      format.html { redirect_to user_exercises_path(@user, @exercise) }
      format.js
    end
  end

  private
  def exercise_params
    params.require(:exercise).permit(:name, :burned, :user_id => current_user.id)
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @users = User.all
    @user = User.find(params[:user_id])
    @foods = User.foods.order('name')
  end

  def new
    @user = User.find(params[:user_id])
    @food = @user.foods.new
  end

  def create
    @user = User.find(params[:user_id])
    @food = @user.foods.new(food_params)
    if @food.save
      flash[:notice] = "Food added."
    else
      render :new
    end
    respond_to do |format|
      format.html { redirect_to user_foods_path(@user, @food) }
      format.js
    end
  end

  def edit
    @user = current_user
    @food = Food.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @food = Food.find(params[:id])
    if @food.update(food_params)
      flash[:notice] = @food.name + ' has been updated.'
      respond_to do |format|
        format.html { redirect_to user_foods_path(@user, @food) }
        format.js
      end
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @food = Food.find(params[:id])
    @food.destroy
    flash[:notice] = @food.name + " has been removed."
    respond_to do |format|
      format.html { redirect_to user_foods_path(@user, @food) }
      format.js
    end
  end

  def sort
    params[:food].each_with_index do |id, index|
      Food.update_all({name: index+1}, {id: id})
    end
    render nothing: true
  end

  private
  def food_params
    params.require(:food).permit(:name, :calories, :user_id => current_user.id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "Logged in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "Problems."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    # @foods = User.foods.order('name')
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    # @user = User.new(user_params)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome"
      redirect_to '/'
    else
      flash[:alert] = 'There was a problem creating your account. Please try again.'
      redirect_to :back
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = @user.name + "Successfully updated."
      redirect_to user_path(user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = @user.name + "successfully deleted!"
    redirect_to users_path
  end

  def sort
    params[:food].each_with_index do |id, index|
      Food.update_all({name: index+1}, {id: id})
    end
    render nothing: true
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/exercises/_exercise.html.erb
<li id="exercise_item_<%= exercise.id %>">
  <p><%= exercise.name %></p>
  <p><%= exercise.burned %></p>
  <%= link_to "Edit", edit_user_exercise_path(@user, exercise), id: "edit_exercise_link", remote: true %> | 
  <%= link_to "Remove", user_exercise_path(@user, exercise), id: "delete_exercise_link", remote: true, data: {method: 'delete', confirm:'are you sure?'} %>
</li>

app/views/exercises/_form.html.erb
<%= simple_form_for [@user, @exercise], remote: true do |f| %>
<%= f.input :name %>
<%= f.input :burned %>
<%= f.button :submit %>
<% end %>

app/views/exercises/create.js.erb
$('#new_exercise').remove();
$('#add_exercise_link').show();
$('#exercises_list').append('<%= j render(@exercise) %>');
$('#burned_total').text('<%= @user.exercises.sum(:burned) %>');
$('#calorie_net').text('<%= @user.foods.sum(:calories) - @user.exercises.sum(:burned) %>');

app/views/exercises/destroy.js.erb
$('#exercise_item_<%= @exercise.id %>').remove();
$('#burned_total').text('<%= @user.exercises.sum(:burned) %>');
$('#calorie_net').text('<%= @user.foods.sum(:calories) - @user.exercises.sum(:burned) %>');

app/views/exercises/edit.js.erb
$('#edit_exercise_link').hide().after('<%= j render("form") %>');
$('#burned_total').text('<%= @user.exercises.sum(:burned) %>');
$('#calorie_net').text('<%= @user.foods.sum(:calories) - @user.exercises.sum(:burned) %>');

app/views/exercises/new.js.erb
$('#add_exercise_link').hide().after('<%= j render("form") %>');
$('#burned_total').text('<%= @user.exercises.sum(:burned) %>');
$('#calorie_net').text('<%= @user.foods.sum(:calories) - @user.exercises.sum(:burned) %>');

app/views/exercises/update.js.erb
$('#edit_exercise_<%= @exercise.id %>').remove();
$('#exercise_item_<%= @exercise.id %>').remove();
$('#exercises_list').append('<%= j render(@exercise) %>');
$('#burned_total').text('<%= @user.exercises.sum(:burned) %>');
$('#calorie_net').text('<%= @user.foods.sum(:calories) - @user.exercises.sum(:burned) %>');

app/views/foods/_food.html.erb
<li id="food_item_<%= food.id %>">
  <p><%= food.name %></p>
  <p><%= food.calories %></p>
  <span class="handle">[drag]</span>
  <%= link_to "Edit", edit_user_food_path(@user, food), id: "edit_food_link", remote: true %> |
  <%= link_to "Remove", user_food_path(@user, food), id: "delete_food_link", remote: true, data: {method: 'delete', confirm:'are you sure?'} %>
</li>

app/views/foods/_form.html.erb
<%= render 'layouts/errors', :object => @food %>
<%= simple_form_for [@user, @food], remote: true do |f| %>
  <%= f.input :name %>
  <%= f.input :calories %>
  <%= f.button :submit %>
<% end %>

app/views/foods/create.js.erb
$('#new_food').remove();
$('#add_food_link').show();
$('#foods_list').append('<%= j render(@food) %>');
$('#calorie_total').text('<%= @user.foods.sum(:calories) %>');
$('#calorie_net').text('<%= @user.foods.sum(:calories) - @user.exercises.sum(:burned) %>');

app/views/foods/destroy.js.erb
$('#food_item_<%= @food.id %>').remove();
$('#calorie_total').text('<%= @user.foods.sum(:calories) %>');
$('#calorie_net').text('<%= @user.foods.sum(:calories) - @user.exercises.sum(:burned) %>');

app/views/foods/edit.js.erb
$('#edit_food_link').hide().after('<%= j render("form") %>');
$('#calorie_total').text('<%= @user.foods.sum(:calories) %>');
$('#calorie_net').text('<%= @user.foods.sum(:calories) - @user.exercises.sum(:burned) %>');

app/views/foods/new.html.erb
<%= render 'form' %>

app/views/foods/new.js.erb
$('#add_food_link').hide().after('<%= j render("form") %>');
$('#calorie_net').text('<%= @user.foods.sum(:calories) - @user.exercises.sum(:burned) %>');

app/views/foods/update.js.erb
$('#edit_food_<%= @food.id %>').remove();
$('#food_item_<%= @food.id %>').remove();
$('#foods_list').append('<%= j render(@food) %>');
$('#calorie_total').text('<%= @user.foods.sum(:calories) %>');
$('#calorie_net').text('<%= @user.foods.sum(:calories) - @user.exercises.sum(:burned) %>');

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix the following errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Health Tracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse" id="my-navbar">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapse" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to "Home", "/", class: "navbar-brand"  %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left special-color">

        </ul>

        <ul class="nav navbar-nav navbar-right special-color">
          <% if current_user %>
          <li><%= link_to @user.email, log_in_path %></li>
          <% else %>
            <li><%= link_to "You must log in", log_in_path %></li>
          <% end %>

          <li><%= link_to 'Log In', log_in_path %></li>
          <li><%= link_to 'Register', new_user_path %></li>

          <li><%= link_to "Log Out", log_out_path %></li>

        </ul>
      </div>

    </div>
  </nav>

  <div class = "container">
    <%= flash[:notice] %>
    <%= flash[:alert] %>

    <%= yield %>
  </div>

</body>
</html>

app/views/users/_form.html.erb
<%=form_for User.new do |f| %>
  <%=f.label :email %>
  <p><%=f.text_field :email %></p>
  <%=f.label :password %>
  <p><%=f.password_field :password %></p>
  <%=f.label :password_confirmation %>
  <p><%=f.password_field :password_confirmation %></p>
  <%=f.submit "Sign Up" %>
<%end%>

app/views/users/index.html.erb
<h1 class="page-header text-center">Welcome to Health Tracker</h1>

<% if current_user %>
<div class="row">
  <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
    <%= link_to 'Add Food', new_user_food_path(@user), id: "add_food_link", :class => "btn btn-success", remote: true %>
    <ul id ="foods_list"> <%= link_to "sort", users_path(direction: 'asc') %>
      <%= render(@user.foods.order('name ' + (params[:food] ? 'asc' : 'desc'))) %>
    </ul>
    <h2>Total Calories Consumed: <span id="calorie_total"><%= @user.foods.sum(:calories) %></span></h2>
  </div>
  <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
    <%= link_to 'Add Exercise', new_user_exercise_path(@user), id: "add_exercise_link", :class => "btn btn-success", remote: true %>
    <ul id ="exercises_list">
      <%= render(@user.exercises) %>
    </ul>
    <h2>Total Calories Burned: <span id="burned_total"><%= @user.exercises.sum(:burned) %></span></h2>
  </div>
</div>
<h2 class="text-center">Net Calories: <span id="calorie_net"><%= @user.foods.sum(:calories) - @user.exercises.sum(:burned) %></span></h2>

<div class="row">
  <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
    <table class="pretty" align="center">
      <tr>
        <th>Exercise</th>
        <th>Calories Burned</th>
      </tr>
      <% for exercise in @user.exercises %>
      <tr>
        <td><%= exercise.name %></td>
        <td><%= exercise.burned %></td>
        <td><%= link_to "Edit", edit_user_exercise_path(@user, exercise), id: "edit_exercise_link", remote: true %> |
          <%= link_to "Remove", user_exercise_path(@user, exercise), id: "delete_exercise_link", remote: true, data: {method: 'delete', confirm:'are you sure?'} %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>


<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

app/views/users/new.js.erb
$('#add_food_link').hide().after('<%= j render("form") %>');